apiVersion: v1
kind: Service
metadata:
  name: openhorizon-control
  labels:
    app: openhorizon-control
spec:
  type: NodeIP
  selector:
    app: openhorizon-control
  ports:
    - name: http
      port: 8080
      targetPort: 8080
